language: php

php:
  - 7.0

env:
  - DATABASE='drupal'
  - DB_USERNAME='root'
  - DB_PASSWORD='root'

mysql:
  database: $DATABASE
  username: $DB_USERNAME
  encoding: $DB_ENCODE

before_install:
  - composer self-update
  - pear channel-discover pear.drush.org
  - sudo apt-get -y php-cgi php-mysql

install:
  - pear install drush/drush

before_script:
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - cat /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - drush dl drupal-7.x --destination=$DRUPAL_ROOT -y
  - drush si minimal --db-url="mysql://$DB_USERNAME@127.0.0.1/$DATABASE" -y
  - echo "require_once 'sites/all/conf/master.settings.inc';" >> $DRUPAL_ROOT/sites/default/settings.php
  - drush -r $DRUPAL_ROOT en master -y
  - drush -r $DRUPAL_ROOT master-ensure-modules --scope=local -y
  - drush -r $DRUPAL_ROOT en ddc_theme -y
  - drush -r $DRUPAL_ROOT vset theme_default ddc_theme -y
  - drush -r $DRUPAL_ROOT dis bartik -y
  - drush -r $DRUPAL_ROOT fr ddc_search ddc_block -y
  - drush -r $DRUPAL_ROOT gent tags 7 -y
  - drush -r $DRUPAL_ROOT genc --types=author 10 0 -y
  - drush -r $DRUPAL_ROOT genc --types=article 500 0 -y
  - drush -r $DRUPAL_ROOT eval 'node_access_rebuild();'
  - drush -r $DRUPAL_ROOT ucrt ronald --password="password"

script:
  - curl "http://127.0.0.1"
